version: '3.7'

services:

  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms4g -Xmx4g  # Increase memory to 8GB
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200


  # PostgreSQL Docker Images: https://hub.docker.com/_/postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase  # Change to your desired database name
      POSTGRES_USER: myuser  # Change to your desired username
      POSTGRES_PASSWORD: mypassword  # Change to your desired password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432


volumes:
  postgres-data:
    driver: local
  elasticsearch-data:
    driver: local

